version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: todo-backend
    environment:
      - DATABASE_URL=sqlite:////data/app.db
      - DEBUG=False
    volumes:
      - sqlite-data:/data
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://51.21.191.178:8000
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped

volumes:
  sqlite-data:
    driver: local
