version: "3.9"
services:
  backend:
    build:
      context: ./backend
    container_name: todo-backend
    env_file:
      - ./backend/.env
    volumes:
      - sqlite-data:/data
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://backend:8000
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  sqlite-data:
